# Generated by Django 3.1.5 on 2021-01-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='coexpression',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='combined_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='cooccurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='database',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='experimental',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='fusion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='neighborhood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='protein1',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AddField(
            model_name='interaction',
            name='protein2',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AddField(
            model_name='interaction',
            name='textmining',
            field=models.IntegerField(default=0),
        ),
    ]
