# Generated by Django 3.1.5 on 2021-01-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0002_auto_20210112_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='coexpression',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='combined_score',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='cooccurance',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='database',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='experimental',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='fusion',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='protein1',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='protein2',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='textmining',
        ),
    ]
