# Generated by Django 3.1.5 on 2021-01-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0003_auto_20210112_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='protein1',
            field=models.CharField(default='NA', max_length=25),
        ),
    ]
