# Generated by Django 3.1.5 on 2021-01-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0004_interaction_protein1'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='fusion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='neighborhood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='protein2',
            field=models.CharField(default='NA', max_length=25),
        ),
    ]
