# Generated by Django 3.1.5 on 2021-01-12 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0005_auto_20210112_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='fusion',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='protein2',
        ),
    ]
