# Generated by Django 3.1.5 on 2021-01-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0006_auto_20210112_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='protein2',
            field=models.CharField(default='NA', max_length=25),
        ),
    ]
