# Generated by Django 3.1.5 on 2021-01-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0007_interaction_protein2'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='neighborhood',
            field=models.IntegerField(default=0),
        ),
    ]
