# Generated by Django 3.1.5 on 2021-01-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0008_interaction_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='fusion',
            field=models.IntegerField(default=0),
        ),
    ]
