# Generated by Django 3.1.5 on 2021-01-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0010_interaction_cooccurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='coexpression',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='experimental',
            field=models.IntegerField(default=0),
        ),
    ]
