# Generated by Django 3.1.5 on 2021-01-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0011_auto_20210112_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='database',
            field=models.IntegerField(default=0),
        ),
    ]
