# Generated by Django 3.1.5 on 2021-01-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0012_interaction_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='textmining',
            field=models.IntegerField(default=0),
        ),
    ]
