# Generated by Django 3.1.5 on 2021-01-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('protein1', models.CharField(default='NA', max_length=25)),
                ('protein2', models.CharField(default='NA', max_length=25)),
                ('neighborhood', models.IntegerField(default=0)),
                ('fusion', models.IntegerField(default=0)),
                ('cooccurance', models.IntegerField(default=0)),
                ('coexpression', models.IntegerField(default=0)),
                ('experimental', models.IntegerField(default=0)),
                ('database', models.IntegerField(default=0)),
                ('textmining', models.IntegerField(default=0)),
                ('combined_score', models.IntegerField(default=0)),
            ],
        ),
    ]
